"""Configuration constants for Provenance Guard."""

SERVICE_NAME = "provenance-guard"
API_VERSION = "v1"

GROQ_MODEL = "llama-3.3-70b-versatile"

GROQ_WEIGHT = 0.65
STYLOMETRIC_WEIGHT = 0.35

LIKELY_HUMAN_MAX = 0.35
LIKELY_AI_MIN = 0.70

LOW_CONFIDENCE_MAX = 0.39
MEDIUM_CONFIDENCE_MAX = 0.74
HIGH_CONFIDENCE_MIN = 0.75

DISTANCE_CONFIDENCE_WEIGHT = 0.45
SIGNAL_CONFIDENCE_WEIGHT = 0.35
AGREEMENT_FACTOR_WEIGHT = 0.20

SIGNAL_DISAGREEMENT_THRESHOLD = 0.35
STRONG_AGREEMENT_MAX_GAP = 0.20

VERY_SHORT_TEXT_MAX_CHARS = 80
SHORT_TEXT_MAX_CHARS = 200
MAX_TEXT_CHARS = 8000

STYLOMETRIC_MIN_AI_LIKELIHOOD = 0.20
STYLOMETRIC_MAX_AI_LIKELIHOOD = 0.80
COMPLEXITY_NORMALIZATION_BOUND = 40
MIN_WORDS_FOR_STABLE_DIVERSITY = 50
MIN_SENTENCES_FOR_STABLE_VARIANCE = 3
READING_WORDS_PER_MINUTE = 200

VOCAB_DIVERSITY_LOW = 0.45
VOCAB_DIVERSITY_HIGH = 0.70
VOCAB_DIVERSITY_AI_NUDGE = 0.08
VOCAB_DIVERSITY_HUMAN_NUDGE = 0.04

SENTENCE_LENGTH_VARIANCE_LOW = 6
SENTENCE_LENGTH_VARIANCE_HIGH = 20
SENTENCE_LENGTH_VARIANCE_AI_NUDGE = 0.08
SENTENCE_LENGTH_VARIANCE_HUMAN_NUDGE = 0.04

PUNCTUATION_DENSITY_LOW = 0.015
PUNCTUATION_DENSITY_HIGH = 0.08
PUNCTUATION_DENSITY_LOW_AI_NUDGE = 0.04
PUNCTUATION_DENSITY_HIGH_AI_NUDGE = 0.02

COMPLEXITY_VARIANCE_LOW = 0.02
COMPLEXITY_VARIANCE_HIGH = 0.08
COMPLEXITY_VARIANCE_AI_NUDGE = 0.05
COMPLEXITY_VARIANCE_HUMAN_NUDGE = 0.03

STYLOMETRIC_BASE_CONFIDENCE = 0.55
STYLOMETRIC_LOW_WORD_COUNT_PENALTY = 0.15
STYLOMETRIC_LOW_SENTENCE_COUNT_PENALTY = 0.15
STYLOMETRIC_SHORT_TEXT_PENALTY = 0.10
STYLOMETRIC_VERY_SHORT_TEXT_PENALTY = 0.20

SUBMIT_RATE_LIMIT_PER_MINUTE = "10 per minute"
SUBMIT_RATE_LIMIT_PER_DAY = "100 per day"
